-- AlterTable
ALTER TABLE "User" ALTER COLUMN "walletAddressETH" SET NOT NULL,
ALTER COLUMN "walletAddressETH" SET DEFAULT '',
ALTER COLUMN "walletAddressETH" SET DATA TYPE TEXT,
ALTER COLUMN "walletAddressSOL" SET NOT NULL,
ALTER COLUMN "walletAddressSOL" SET DEFAULT '',
ALTER COLUMN "walletAddressSOL" SET DATA TYPE TEXT;
